"""empty message

Revision ID: 5ebc5ebfc306
Revises: 2845f4c5398a
Create Date: 2022-11-30 19:16:48.208929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ebc5ebfc306'
down_revision = '2845f4c5398a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('giveaway', 'issuer_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.add_column('item', sa.Column('obtain_action', sa.String(), nullable=False))
    op.alter_column('item', 'giveaway_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'giveaway_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('item', 'obtain_action')
    op.alter_column('giveaway', 'issuer_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
