"""Add value field to Item

Revision ID: a1e51a666c3d
Revises: fe66dc1dd29f
Create Date: 2022-12-23 11:54:59.832932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e51a666c3d'
down_revision = 'fe66dc1dd29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('value', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'value')
    # ### end Alembic commands ###
