"""empty message

Revision ID: f4131cd513ea
Revises: 5a7ed50df2db
Create Date: 2022-11-30 17:59:59.340736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4131cd513ea'
down_revision = '5a7ed50df2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaway',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('issuer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('obtainable', sa.Boolean(), nullable=False),
    sa.Column('winner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('giveaway_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('giveaway_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'giveaway_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup')
    op.drop_table('item')
    op.drop_table('giveaway')
    # ### end Alembic commands ###
